server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/

spring:
  application:
    name: config-server
  rabbitmq:
    host: ${RABBIT_MQ_HOST:111.231.66.170}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/springcloud/config.git
          search-paths: /
management:
  endpoints:
    web:
      exposure:
        include: '*'